#ifndef CONNECT_INTERNAL_H
#define CONNECT_INTERNAL_H

#include "mister/connect.h"

enum CONNECT_MDATA_FIELDS { // Same order as CONNECT_MDATA_TEMPLATE
    CONNECT_PACKET_TYPE,
    CONNECT_REMAINING_LENGTH,
    CONNECT_PROTOCOL_NAME,
    CONNECT_PROTOCOL_VERSION,
    CONNECT_RESERVED,
    CONNECT_CLEAN_START,
    CONNECT_WILL_FLAG,
    CONNECT_WILL_QOS,
    CONNECT_WILL_RETAIN,
    CONNECT_PASSWORD_FLAG,
    CONNECT_USERNAME_FLAG,
    CONNECT_MR_FLAGS,
    CONNECT_KEEP_ALIVE,
    CONNECT_MR_PROPERTIES,
    CONNECT_PROPERTY_LENGTH,
    CONNECT_SESSION_EXPIRY_INTERVAL,
    CONNECT_RECEIVE_MAXIMUM,
    CONNECT_MAXIMUM_PACKET_SIZE,
    CONNECT_TOPIC_ALIAS_MAXIMUM,
    CONNECT_REQUEST_RESPONSE_INFORMATION,
    CONNECT_REQUEST_PROBLEM_INFORMATION,
    CONNECT_USER_PROPERTIES,
    CONNECT_AUTHENTICATION_METHOD,
    CONNECT_AUTHENTICATION_DATA,
    CONNECT_CLIENT_IDENTIFIER,
    CONNECT_WILL_PROPERTY_LENGTH,
    CONNECT_WILL_DELAY_INTERVAL,
    CONNECT_PAYLOAD_FORMAT_INDICATOR,
    CONNECT_MESSAGE_EXPIRY_INTERVAL,
    CONNECT_CONTENT_TYPE,
    CONNECT_RESPONSE_TOPIC,
    CONNECT_CORRELATION_DATA,
    CONNECT_WILL_USER_PROPERTIES,
    CONNECT_WILL_TOPIC,
    CONNECT_WILL_PAYLOAD,
    CONNECT_USER_NAME,
    CONNECT_PASSWORD
};

#endif // CONNECT_INTERNAL_H
